### ISSUE TITLE
Compatibility for Azure Web Apps and different OS

### ISSUE THREAD

**Issue by grahambunce** [richard-scryber/scryber.core#22] opened 2020-10-06 20:57 UTC
Hi,

Thanks for the library - can you confirm if this runs in Azure Web Apps (both windows and linux variants)? Also do you know if it works on MacOS?

Thanks

**Comment by richard-scryber** [comment] 2020-10-19 17:21
Hi Graham - slow response from me, but yes. I can confirm it works on Azure Web Apps, not tried the linux variance, but I have converted to dotnet.core using VS Code on a Mac.
There is a GDIPlus library needed for Macs that is a detailed here. 
https://scrybercore.readthedocs.io/en/latest/libgdiplus.html

Hope this helps. Let me know if you have issues. Always happy to help.

**Comment by ggrgovski** [comment] 2020-11-04 14:23
Hi,

I have same question but this time for Azure App Service on Linux ?
I have tried and the pictures are working and the background color for example, but the text is not rendered when I host it on Linux and it works on Windows, any idea ?

Thanks

**Comment by richard-scryber** [comment] 2020-11-04 17:52
Hi - sounds like the font you are trying to use is not available on the system, or the font's path is not finding the true type font file. The options can be used to configure the location of the fonts directory, or you can add them explicitly to the paths.

If you change to a true type (or open type) font you know is available, or added to your system, then it should be available for use and embedding.

The settings.json file can also be extended to include the font. We will add some documentation on this, but the format is..

"Scryber": {
    "Fonts": {
      "DefaultDirectory": "Mocks/Fonts/Avenir",
      "UseSystemFonts": "True",
      "FontSubstitution": "true",
      "DefaultFont": "Avenir Next Condensed",
      "Register": [
        {
          "Family": "Segoe UI",
          "File": "Mocks/Fonts/segoeui.ttf"
        },
        {
          "Family": "Segoe UI",
          "Style": "Bold",
          "File": "Mocks/Fonts/segoeuib.ttf"
        },
        {
          "Family": "Segoe UI",
          "Style": "Italic",
          "File": "Mocks/Fonts/segoeuii.ttf"
        }
      ]
    }

**Comment by ggrgovski** [comment] 2020-11-04 19:59
Hi Richard,

Thanks for this fast response.
I think that it's not the issue with the Font, because I tried with some other Fonts and it was throwing an error on generating of the pdf file. Now I'm using the default ones and it's not failing on generating of the PDF file it's just not rendering the text and the images are presented, could be something with the GDI libraries ?

The content of my pdfx file looks like this:

<Content>
        <doc:Div styles:class="std-font" styles:font-family="Helvetica" >
          <doc:Span>Helvetica is the default font.</doc:Span>
        </doc:Div>
        <doc:Div styles:class="std-font" styles:font-family="Times" >
          <doc:Span>Times is a standard font.</doc:Span>
        </doc:Div>
        <doc:Div styles:class="std-font" styles:font-family="Courier" >
          <doc:Span>Courier is a standard font.</doc:Span>
        </doc:Div>
        <doc:Div styles:class="std-font" styles:font-family="Zapf Dingbats" >
          <doc:Span>Dingbats is a standard font.</doc:Span>
        </doc:Div>
        <doc:Div styles:class="std-font" styles:font-family="Symbol" >
          <doc:Span>Symbol is a standard font.</doc:Span>
        </doc:Div>

        <doc:Div styles:class="img-wrap" >
          

          <doc:Div styles:class="std-font" styles:font-family="Helvetica" >
            <doc:Span> Image that does not exist</doc:Span>
          </doc:Div>
          <doc:Image src="./Content/Images/NotFound.png" />

          <doc:Div styles:class="std-font" styles:font-family="Helvetica" >
            <doc:Span> PNG 32bit Image with alpha channel</doc:Span>
          </doc:Div>
          <doc:Image src="./Content/Images/Toroid32.png" />

        </doc:Div>
        
      </Content>


And this is how it looks when the pdf file is generated:

![image](https://user-images.githubusercontent.com/3037725/98161784-9bc7c400-1ee0-11eb-83cb-53dcea4374c1.png)

**Comment by richard-scryber** [comment] 2020-11-05 09:21
I'm going to give it a go myself, and see what I can do.

However, you could try and append the travelog to the file using the processing instructions, at the top of the file (after the <?xml ?> processing instruction.

<?scryber append-log='true' log-level='Messages' parser-log='true' ?>

**Comment by ggrgovski** [comment] 2020-11-05 10:38
Even then I'm not able to see the log text when it's on Linux App Service.
[pdf1.pdf](https://github.com/richard-scryber/scryber.core/files/5493703/pdf1.pdf)

**Comment by richard-scryber** [comment] 2020-11-05 16:08
Thanks for the attachment. At least we can see there were errors. Looks like the string measurements are coming back as zero size for the built in font measurement in GDI+ library.
I'm checking it out, but if you want to...
Try including a ttf file in your distribution, and registering it using the configuration settings as above.

**Comment by ggrgovski** [comment] 2020-11-05 18:21
Hi Richard,

I tried with a custom font, but for some reason I'm getting error, most probably I don't know how to specify the Font Settings.

1. This is the error that I'm getting
![image](https://user-images.githubusercontent.com/3037725/98280354-911e3500-1f9b-11eb-8dae-2c7e1da39429.png)

2. This is how I'm specifying the settings. I tried in appsettings.json and also I create new file settings.json
![image](https://user-images.githubusercontent.com/3037725/98280550-dcd0de80-1f9b-11eb-9eff-c0c93d15b7d1.png)
![image](https://user-images.githubusercontent.com/3037725/98280580-e35f5600-1f9b-11eb-89a5-b222193ec0ea.png)

3. These is the font file that is a content that is copied when new
![image](https://user-images.githubusercontent.com/3037725/98280685-08ec5f80-1f9c-11eb-803c-dbf0f62551da.png)


Can you give me some instructions what is my issue ?

**Comment by richard-scryber** [comment] 2020-11-08 12:25
Hi - are you loading the settings file in your start up execution?

**Comment by ggrgovski** [comment] 2020-11-08 15:24
Hey Richard, can you please specify how to load the settings file in Startup.cs ?

**Comment by ggrgovski** [comment] 2020-11-08 16:39
Hi Richard,

Thanks for your time. Actually I fount how to load the settings and it goes through services.AddScryberServices(IConfiguration);.
That actually helped me out and I have specified all of the .ttf files and now the whole document is rendered even on Linux.

Have a great day and thanks again,
Gjorgji

**Comment by ggrgovski** [comment] 2020-11-09 09:46
Hi Richard,

Because your documentation is still in progress, can you please give me an example of .pdfx file let's say where there is a table rendered.
I tried to find and example but I was not able.
I need that for creating an invoice document.

Thanks.

**Comment by richard-scryber** [comment] 2020-11-09 13:06
Hi Gjorgji - there is some documentation on tables including headers and binding to sources here...
[https://scrybercore.readthedocs.io/en/latest/component_tables.html](https://scrybercore.readthedocs.io/en/latest/component_tables.html).
If you are having issues or need help, just shout.

And glad that the fonts are sorted

**Comment by ggrgovski** [comment] 2020-11-09 14:14
Hi Richard,

Thanks for pointing out. I think this will help me to make a template for invoice.

**Comment by richard-scryber** [comment] 2020-11-11 08:56
I'll see if can put something together for next week. There is an example of binding on a for-each loop in the table docs if that helps. [https://scrybercore.readthedocs.io/en/latest/component_tables.html#binding-to-data](https://scrybercore.readthedocs.io/en/latest/component_tables.html#binding-to-data)

**Comment by ggrgovski** [comment] 2020-11-11 09:23
Hi Richard,

Because I spent some time on generating this .pdfx file for our invoice I want to share with all of you my template.

https://drive.google.com/file/d/1lp45SjqwqGHqbbxmPxDUpElwyyvxHNGz/view?usp=sharing

**Comment by richard-scryber** [comment] 2020-11-11 09:32
That's brilliant Gjorgji. I'm really please to see you using the @ Model parameter capability. It's something we added when porting to DotNet.Core and is a brilliant example.

I hope once the teething troubles with installation were sorted, it was easy to build. We have done a bit with css and html too, that needs documenting.

**Comment by ggrgovski** [comment] 2020-11-11 11:02
That is great feature, I really liked it and I can bind my template dynamically with that model, which is perfect.

To be honest this is one of the most useful library and really great implementation done from your side.
You probably just miss some more documentation, but everything else is perfect.

I'm glad that I can use this one, and I'm also open for contribution or any other collaboration if needed.

Thanks, hope my example will also be useful for someone else.

**Comment by richard-scryber** [comment] 2021-02-28 09:27
Hi Gjorgji. I hope things are going well with you. 

Going to close this one to tidy up a bit, as fixed in .net 5 and supporting font face on the library.

**Closed by richard-scryber** 2021-02-28 09:27 UTC
